services:
  bot:
    container_name: bot
    build: ./bot
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - TOKEN=${TOKEN}
      - DBHOST=${DBHOST}
      - DBPORT=${DBPORT}
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
      - DBNAME=botdb
    env_file:
      - .env
    volumes:
      - ./bot/logs:/bot/logs

  db:
    container_name: db
    build: ./db
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_DB: botdb
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data/

    
  db_repl:
    container_name: db_repl
    build: ./db_repl
    environment:
      POSTGRES_PASSWORD: ${DBPASSWORD}
      PGUSER: replicator
      PGPASSWORD: replicator_password
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db: